import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ApolloWrapper } from './ApolloWrapper';
import { ThemeProvider } from '@/components/ui/ThemeProvider';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import AuthProvider, { AuthenticationGuard } from './contexts/AuthProvider';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
}) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <StoreProvider>
        <ApolloWrapper>
          <body className={inter.className}>
            <ThemeProvider
              attribute='class'
              defaultTheme='system'
              enableSystem
              disableTransitionOnChange
            >
              <NextIntlClientProvider locale={locale} messages={messages}>
                <AuthProvider>{children}</AuthProvider>
              </NextIntlClientProvider>
            </ThemeProvider>
          </body>
        </ApolloWrapper>
      </StoreProvider>
    </html>
  );
}
